# Copyright (c) 2022 Himanshu Goel
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

CC=g++
CFLAGS=-Wall -Wextra -Werror -std=c++11 -O3

OBJS=main.o

all: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o generator